[package]
name = "advent-of-code-2025"
version = "0.1.0"
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1.12.2"
handlebars = "6.3.2"
serde_json = "1.0.145"
num-traits = "0.2.19"
